#action.yml
name: 'List User Repos Action'
description: 'Lista branches de um repositório público'
branding:
  icon: 'git-branch'
  color: 'blue'
inputs:
  owner: # id do input
    description: 'Sua organização ou usuário github'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    
#image: 'docker://geovana10/list-branches-action:v1'
